# Generated by Django 3.2.25 on 2025-06-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profileinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
