# Generated by Django 3.2.25 on 2025-06-24 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_profileinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='github',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
