# Generated by Django 3.2.25 on 2025-06-24 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_profileinfo_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='linkedin',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
