# Generated by Django 3.2.25 on 2025-07-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_profileinfo_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=50)),
                ('end_date', models.DateField(max_length=50)),
                ('university', models.CharField(max_length=250)),
            ],
        ),
    ]
